### ISSUE TITLE
Not working with Homey 2.0 beta

### ISSUE THREAD

**Issue by mbnn** [DirkdeDraak/homey-integra-alarm#2]
Hello,

With Homey 2.0 beta this app crashes as soon as you want to arm/disarm.
Connection errors is what it gives after it crashes.

I've made a diagnostic report: 69f0bbbe-62cf-4404-befa-c564712e45cd

**Comment by mickelluiten** [comment]
Hi,  did run the app from development athom-cli.
Below the lines from log : 

2018-12-12 00:13:54 [log] [integraAlarm] org.myalarm.integra running...
2018-12-12 00:13:54 [log] [ManagerDrivers] [satelIntegra] [0] Initialize device
2018-12-12 00:13:54 [log] [ManagerDrivers] [satelIntegra] [0]  * Name: Integra Alarm
2018-12-12 00:13:54 [log] [ManagerDrivers] [satelIntegra] [0]  * Driver: satelIntegra
2018-12-12 00:13:54 [log] [ManagerDrivers] [satelIntegra] [0]  * Class: homealarm
2018-12-12 00:13:54 [log] [ManagerDrivers] [satelIntegra] [0]  * Available:  true
2018-12-12 00:13:54 [log] [ManagerDrivers] [satelIntegra] [0]  * Capabilities: [ 'onoff' ]
2018-12-12 00:13:55 [log] [ManagerDrivers] [satelIntegra] [0]  * State: { onoff: null }
2018-12-12 00:13:55 [log] [ManagerDrivers] [satelIntegra] [0]  * Settings:  { alarmaddr: '192.168.2.1',
  alarmport: 7094,
  alarmcode: ****
  alarmpart: '1',
  alarmpoll: 5000,
  alarmtype: '?',
  alarmvers: '?',
  alarmlang: '?' }
2018-12-12 00:14:23 [log] [ManagerDrivers] [satelIntegra] [0] STATE CHANGE DETECTED to: true
2018-12-12 00:14:23 [log] [ManagerDrivers] [satelIntegra] [0] HomeAlarm state changed to: armed ( true )
/drivers/satelIntegra/device.js:38
    str = str.toString(); // force to be string
              ^

TypeError: Cannot read property 'toString' of undefined
    at stringToHexBytes (/drivers/satelIntegra/device.js:38:15)
    at integraAlarmDevice.armAction (/drivers/satelIntegra/device.js:490:26)
    at integraAlarmDevice.getCommand_arm (/drivers/satelIntegra/device.js:503:21)
    at registerCapabilityListener (/drivers/satelIntegra/device.js:294:42)
    at integraAlarmDevice.__onCapability (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Device.js:1:1934)
    at emitTwo (events.js:126:13)
    at integraAlarmDevice.emit (events.js:214:7)
    at integraAlarmDriver.__onCapability (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:1511)
    at emitTwo (events.js:126:13)
    at integraAlarmDriver.emit (events.js:214:7)

--- INFO: org.myalarm.integra has been killed --- 

Maybe this helps to fix the problem?
MIckel
